### ISSUE TITLE
README.md to-do

### ISSUE THREAD

**Issue by kmcdermo** [trackreco/mkFit#163]
Hi all, 

Here is a running list of things we should add to the README.md (or create additional text files and link them to the README).  Feel free to check the boxes as we go, making sure to point to the PR. I attached names as suggestions for these new sections.

- [x] CMSSW Integration best practices + suggestions: @makortel @slava77 
- [ ] GPU Code: the next Matthieu (@dan131riley , @slava77 perhaps with the hackathon you might be able to add some notes?)
- [x] Hit index meanings @areinsvo for -9; @osschar for -2, -3; -1 == missed hit

**Comment by areinsvo** [comment]
I'm trying to clean up some of the open github issues before our face to face. The only remaining item on this to-do list is to document Matthieu's GPU code, but the window for that has probably closed. Does anyone have any additional requests for the documentation? If I don't hear anything by next Wednesday, I will close this issue and we can open a new one if something comes up.

**Comment by srlantz** [comment]
I agree that this old issue can be closed, but I think the README.md is again out of step with current practices. For example, it's likely that the paths to datafiles are out of date because Slava has created newer versions of the files to match mkFit updates. "README needs reviewing" might be the appropriate name for a new issue.
